version: '1.0.{build}'

image: Visual Studio 2015 

configuration:
  - Release

environment:
  CMAKE_GENERATOR: "NMake Makefiles JOM"
  QT5: C:\Qt\5.11.0\msvc2015_64
  PLATFORM: X64
  VSVER: 14

install:
  - vcpkg upgrade
  - vcpkg list
  - vcpkg install
        alembic
        --triplet %PLATFORM%-windows
  - vcpkg list
 
before_build:
  - set PATH=C:\Qt\Tools\QtCreator\bin;%PATH%

# build_script:
#     - ps: $env:VSCOMNTOOLS=(Get-Content ("env:VS" + "$env:VSVER" + "0COMNTOOLS"))
#     - md build
#     - cd build
#     - cmake .. -G "%CMAKE_GENERATOR%"
#             -DCMAKE_PREFIX_PATH=%QT5%
#             -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake

#     - "%VSCOMNTOOLS%\..\..\VC\vcvarsall.bat" x86_amd64
#     - cmake --build . --config %CONFIGURATION%
 
build:
 
# comment the above and uncomment the following to just build the dependencies
build_script:
 - echo "Dependencies installed."
 
cache:
  c:\tools\vcpkg\installed\
 